spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    redis:
      time-to-live: 10m
  data:
    redis:
      host: localhost
      port: 6379